# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: SnykSecurityScan@1
  inputs:
      serviceConnectionEndpoint: 'Snyk'
      testType: 'app'
      monitorWhen: 'always'
      failOnIssues: false
      projectName: 'frontend-TIComo'
      organization: 'carlosphin'
      testDirectory: 'frontend-TIComo'

- script: |
    cd backend-TIComo
    mvn snyk:test -DSNYK_TOKEN=e4a4a170-caa1-420f-a9a8-ff9988f61919
  displayName: 'Backend Snyk'