trigger:
- main
- develop
pool:
    vmImage: ubuntu-latest
steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'backend-TIComo/pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    goals: 'clean test'
